name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Player-1.0.1-jar-with-dependencies.jar"
          body: "New version released"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: A new Release requires new Release Notes
          body: Job completed ${{job.status}}
          to: ${{secrets.MAIL_SENDER_TO}}
          from: Release Automation