on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release Flow

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Package
        run: sudo apt-get install xvfb &&
              Xvfb :99 &>/dev/null & export DISPLAY=":99" &&
              mvn package
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            A new release has been created
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: target/Player-1.0.1-jar-with-dependencies.jar
          asset_name: executable.jar
          asset_content_type: application/java-archive
      - name: Send some mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: A new Release requires new Release Notes
          body: Build job of ${{github.repository}} completed successfully!
          to: ${{secrets.MAIL_SENDER_TO}}
          from: Me
