name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "version-executable"
          bodyFile: "readme.md"
          token: ${{ secrets.GITHUB_TOKEN }}
